In [ ]:
import pandas as pd

dataset = pd.read_csv(
    "../dataset.csv",
    low_memory=False,
    dtype_backend="pyarrow"
)
dataset.to_parquet("../dataset.parquet")
dataset.shape

(2596041, 41)

In [1]:
import pandas as pd

df = pd.read_parquet("../dataset.parquet")
print(df.shape)

(2596041, 41)

In [5]:
# Data dsecription
# df.shape
df.info(memory_usage='deep')
df.describe(include='all').transpose().head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2596041 entries, 0 to 2596040
Data columns (total 41 columns):
 #   Column                          Dtype
---  ------                          -----
 0   Unique Key                      int64[pyarrow]
 1   Created Date                    string
 2   Closed Date                     string
 3   Agency                          string
 4   Agency Name                     string
 5   Complaint Type                  string
 6   Descriptor                      string
 7   Location Type                   string
 8   Incident Zip                    string
 9   Incident Address                string
 10  Street Name                     string
 11  Cross Street 1                  string
 12  Cross Street 2                  string
 13  Intersection Street 1           string
 14  Intersection Street 2           string
 15  Address Type                    string
 16  City                            string
 17  Landmark                        string
 18  Facility Type                   string
 19  Status                          string
 20  Due Date                        string
 21  Resolution Description          string
 22  Resolution Action Updated Date  string
 23  Community Board                 string
 24  BBL                             int64[pyarrow]
 25  Borough                         string
 26  X Coordinate (State Plane)      int64[pyarrow]
 27  Y Coordinate (State Plane)      int64[pyarrow]
 28  Open Data Channel Type          string
 29  Park Facility Name              string
 30  Park Borough                    string
 31  Vehicle Type                    string
 32  Taxi Company Borough            string
 33  Taxi Pick Up Location           string
 34  Bridge Highway Name             string
 35  Bridge Highway Direction        string
 36  Road Ramp                       string
 37  Bridge Highway Segment          string
 38  Latitude                        double[pyarrow]
 39  Longitude                       double[pyarrow]
 40  Location                        string
dtypes: double[pyarrow](2), int64[pyarrow](4), string(35)
memory usage: 2.0 GB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Unique Key,2596041.0,<NA>,<NA>,<NA>,64965040.664702,801002.428879,63572086.0,64272063.0,64961031.0,65661097.0,66353317.0
Created Date,2596041,2185289,07/29/2025 07:35:00 PM,110,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Closed Date,2487264,1817546,07/08/2025 03:00:00 PM,873,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Agency,2596041,15,NYPD,1284474,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Agency Name,2596041,15,New York City Police Department,1284474,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Complaint Type,2596041,189,Illegal Parking,438097,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Descriptor,2527273,938,Loud Music/Party,357373,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location Type,2264651,147,Street/Sidewalk,878708,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Incident Zip,2573395,323,10466,82243,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Incident Address,2499861,490518,655 EAST 230 STREET,54343,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Missing Data
missing = df.isna().sum().sort_values(ascending=False)
missing_pct = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    "Missing Values": missing,
    "% of Total": missing_pct
})
missing_df.head(50)

                                Missing Values  % of Total
Taxi Company Borough                   2594226   99.930086
Road Ramp                              2589172   99.735405
Bridge Highway Direction               2588392   99.705359
Facility Type                          2586721   99.640992
Due Date                               2583574   99.519769
Bridge Highway Segment                 2581985   99.458560
Bridge Highway Name                    2581953   99.457328
Taxi Pick Up Location                  2570197   99.004484
Vehicle Type                           2474136   95.304196
Landmark                                898205   34.599030
Intersection Street 1                   706391   27.210318
Intersection Street 2                   705039   27.158238
Cross Street 1                          597209   23.004606
Cross Street 2                          596516   22.977911
Location Type                           331390   12.765207
BBL                                     303458   11.689261
City                                    121873    4.694571
Closed Date                             108777    4.190111
Street Name                              96270    3.708339
Incident Address                         96180    3.704872
Resolution Description                   86512    3.332459
Descriptor                               68768    2.648957
Resolution Action Updated Date           53187    2.048773
Longitude                                41437    1.596161
Location                                 41437    1.596161
Latitude                                 41437    1.596161
X Coordinate (State Plane)               41433    1.596007
Y Coordinate (State Plane)               41408    1.595044
Incident Zip                             22646    0.872328
Address Type                             10676    0.411242
Park Facility Name                        4209    0.162131
Unique Key                                   0    0.000000
Agency Name                                  0    0.000000
Complaint Type                               0    0.000000
Created Date                                 0    0.000000
Agency                                       0    0.000000
Status                                       0    0.000000
Community Board                              0    0.000000
Park Borough                                 0    0.000000
Borough                                      0    0.000000
Open Data Channel Type                       0    0.000000

In [ ]:
df.iloc[:, 1:].nunique().sort_values(ascending=False).head(50)

Created Date                      2185289
Closed Date                       1817546
Resolution Action Updated Date    1679108
Location                           501879
Longitude                          501873
Latitude                           501871
Incident Address                   490518
BBL                                359647
Y Coordinate (State Plane)         123436
X Coordinate (State Plane)         110528
Cross Street 1                      17013
Cross Street 2                      16803
Taxi Pick Up Location               13685
Street Name                         11512
Intersection Street 2               11012
Intersection Street 1               10639
Landmark                             8791
Due Date                             7967
Park Facility Name                   1456
Descriptor                            938
Bridge Highway Segment                927
Resolution Description                738
Road Ramp                             378
Incident Zip                          323
Bridge Highway Direction              223
Complaint Type                        189
City                                  164
Location Type                         147
Bridge Highway Name                    84
Community Board                        77
Agency                                 15
Agency Name                            15
Vehicle Type                            9
Status                                  7
Borough                                 6
Address Type                            6
Park Borough                            6
Taxi Company Borough                    5
Open Data Channel Type                  5
Facility Type                           1
dtype: int64

In [17]:
duplicate_count = df.iloc[:, 1:].duplicated().sum()
print(f"Duplicate rows: {duplicate_count}")

Duplicate rows: 14139